pipeline:

  build:
    image: node
    commands:
      - node --version
      - npm ci
      - npm run build

  deploy:
    image: rclone/rclone
    commands:
      - "rclone sync build/ :sftp: --sftp-host frontier.gwei.cz --sftp-user eb2-website-dev --sftp-port 2022 --sftp-pass $RCLONE_PASS -v"
    secrets: [RCLONE_PASS]
    when:
      branch: [main]

  deploy_ipfs:
    image: ipfs/ipfs-cluster
    commands:
      - ipfs-cluster-ctl --host /dns/ipfs-cluster.gwei.cz/tcp/443 --basic-auth ethbrno:$IPFS_CLUSTER_PASS add -r -w build/
    secrets: [IPFS_CLUSTER_PASS]
