pipeline:
  build:
    image: jarredsumner/bun:0.2.0
    commands:
      - bun --version
      - bun i
      - bun run build
  deploy:
    image: rclone/rclone
    commands:
      - "rclone sync build/ :sftp: --sftp-host frontier.gwei.cz --sftp-user eb2-website-dev --sftp-port 2022 --sftp-pass $RCLONE_PASS -v"
    secrets: [RCLONE_PASS]
    when:
      branch: [main]
